name=input("Enter your name: ")
upper_name=name.upper()
lower_name=name.lower()
title_name=name.title()
name_=name.strip()
_name=name_.lower()
user_name=_name.replace(" ","_")
print("Original Name: ",name)
print("Upper Case Name: ",upper_name)
print("Lower Case Name: ",lower_name)
print("Title Case Name: ", title_name)
print("Your User Name: ",user_name)